export const BEGIN_GET_LIST_BLOG = 'BEGIN_GET_LIST_BLOG';
export const GET_LIST_BLOG_SUCCESS = 'GET_LIST_BLOG_SUCCESS';
export const BEGIN_REFRESH_NEWFEED = "BEGIN_REFRESH_NEWFEED";
export const REFRESH_NEWFEED_SUCCESS = "REFRESH_NEWFEED_SUCCESS";
export const REFRESH_NEWFEED_ERROR = "REFRESH_NEWFEED_ERROR";
export const BEGIN_GET_MORE_LIST_BLOG = 'BEGIN_GET_MORE_LIST_BLOG';
export const GET_MORE_LIST_BLOG_SUCCESS = 'GET_MORE_LIST_BLOG_SUCCESS';

export const BEGIN_GET_BLOG = 'BEGIN_GET_BLOG';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';

export const BEGIN_GET_BOOK = 'BEGIN_GET_BOOK';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
// DETAIL BOOK
export const BEGIN_GET_DETAIL_BOOK = 'BEGIN_GET_DETAIL_BOOK';
export const GET_SUCCESS_DETAIL_BOOK = 'GET_SUCCESS_DETAIL_BOOK';
export const GET_ERROR_DETAIL_BOOK = 'GET_ERROR_DETAIL_BOOK';
// BUY BOOK
export const BEGIN_ORDER_BOOK = "BEGIN_ORDER_BOOK";
export const ORDER_BOOK_SUCCESS = "ORDER_BOOK_SUCCESS";
export const ORDER_BOOK_ERROR   = "ORDER_BOOK_ERROR";
export const ORDER_BOOK_DONE    = "ORDER_BOOK_DONE";
// CURRICULUM
export const BEGIN_GET_CURRICULUM = "BEGIN_GET_CURRICULUM";
export const GET_CURRICULUM_SUCCESS = "GET_CURRICULUM_SUCCESS";
// COURSE
export const BEGIN_GET_COURSE = "BEGIN_GET_COURSE_INFORMATION";
export const GET_COURSE_SUCCESS = "GET_COURSE_INFORMATION_SUCCESS";